webtoon-today/design-system

.github/workflows/chromatic.yml, package-lock.json, package.json, packages/utils/Drawer/src/PortalDrawer.stories.tsx
```python
```
- chromatic을 이용하여 Storybook를 배포합니다.
- chromatic 배포시 Error가 포함된 Story가 포함되면 안되서 Error 스토리를 제거합니다.
-
=> [Chore] chromatic을 이용하여 Storybook를 배포합니다.

.github/workflows/deploy.yml, .npmrc, README.md, package-lock.json, package.json
```python
```
- npm과 node의 버전을 정상적인 deps 설치를 위해서 제한합니다.
```bash
$ nvm use v16
Now using node v16.20.2 (npm v8.19.4)
$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: design-system@1.1.0
npm ERR! notsup Not compatible with your version of node/npm: design-system@1.1.0
npm ERR! notsup Required: {"node":">=18.0.0","npm":">=10.0.0"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
```
```diff
// package.json
+ "engines": {
+  "node": ">=18.0.0",
+  "npm": ">=10.0.0"
+},
```
-
=> [Chore] node, npm version을 제한합니다.

dist/useSortableTable/index.js, packages/dataDisplay/useSortableTable/src/useSortableTable.stories.tsx, packages/dataDisplay/useSortableTable/src/useSortableTable.tsx
```python
```
- `useEffect`에 `if (data.length === 0) { return }`을 추가하여 무한 호출을 방지합니다.
- 데이터 추가, 삭제 스토리를 추가합니다.
-
=> [Bugfix][useSortableTable] 데이터의 길이가 0일 때 useEffect가 무한히 호출되는 현상을 해결합니다.

.github/workflows/deploy.yml, .npmrc, .storybook/main.ts, README.md, dist/useSortableTable/index.js, docs/package-lock.json, docs/package.json, package-lock.json, package.json, packages/dataDisplay/useSortableTable/src/useSortableTable.stories.tsx, packages/dataDisplay/useSortableTable/src/useSortableTable.tsx
- https://github.com/webtoon-today/design-system/pull/29
- https://github.com/webtoon-today/design-system/pull/32 
- https://github.com/webtoon-today/design-system/pull/33
- https://github.com/webtoon-today/design-system/pull/34
- close #39
=> [Release] v1.2.0

dist/Drawer/index.js, packages/utils/Drawer/src/NestedCascadeDrawer.tsx, packages/utils/Drawer/src/PortalDrawer.stories.tsx
```python
```
- 가장 최상위 드로워가 esc key down 이벤트에 의해 닫히도록 합니다.
-
=> [Feature][drawer] esc 키를 눌러 드로워가 닫히게 합니다.

dist/Drawer/index.js, dist/Toast/index.d.ts, dist/Toast/index.js, package-lock.json, package.json, packages/feedback/Toast/src/Recoil/Toast.ts, packages/feedback/Toast/src/Toast.stories.tsx, packages/feedback/Toast/src/Toast.tsx, packages/feedback/Toast/src/main.ts, packages/utils/Drawer/src/NestedCascadeDrawer.tsx, packages/utils/Drawer/src/PortalDrawer.stories.tsx, packages/utils/Drawer/src/useAnimation.tsx
- https://github.com/webtoon-today/design-system/pull/38 
- https://github.com/webtoon-today/design-system/pull/35 
- https://github.com/webtoon-today/design-system/pull/41
=> [Release][240619] v1.3.0

dist/Toast/index.d.ts, dist/Toast/index.js, packages/feedback/Toast/src/Toast.tsx
```python
```
- 메시지가 없는 경우 토스트를 렌더링 하지 않게 합니다.
-
=> [Bugfix][toast] 메시지가 없을 때 토스트가 표시되지 않게합니다.

README.md, package-lock.json, package.json
```python
```
- npm 버전 제한을 제거합니다.
-
=> [Chore] npm 버전 제한을 제거합니다.

README.md, dist/Toast/index.d.ts, dist/Toast/index.js, package-lock.json, package.json, packages/feedback/Toast/src/Toast.tsx
- https://github.com/webtoon-today/design-system/pull/44
- https://github.com/webtoon-today/design-system/pull/46
=> [Release] v1.3.1

packages/input/GuideTextBoxs/src/Functions.ts, packages/input/GuideTextBoxs/src/GuideTextBoxs.scss, packages/input/GuideTextBoxs/src/GuideTextBoxs.tsx
```python
```
- 메트릭에서 사용하는 가이드 텍스트 박스를 디자인 시스템에 추가하기 위해서 복사해 가져 왔습니다.
- 여기에 기본 설정과 stories를 추가해 스토리 북으로 테스트가 가능하게 만들고 있습니다.
- 다른 수정 없이 작동하는 코드를 가져온 것이기 때문에 문제 없이 머지가 가능합니다.
-
=> [Feature] 메트릭에서 가이드 텍스트 박스를 복사해 가져옵니다.

configs/rollup/package.json, package-lock.json, package.json
```python
```
- 메인에 명시된 rollup 관련 devDependecy를 rollup-config 패키지로 옮깁니다.
- 패키지를 옮긴 후 `npm run build`에서 rollup이 정상적으로 동작함을 확인하였습니다.
-
=> [Chore] 메인에 명시된 rollup 관련 devDeps를 configs/rollup으로 옮깁니다.

docs/package-lock.json, docs/package.json, package-lock.json, package.json
```python
```
- react scripts에서 웹소켓의 header의 길이를 무한히 늘리는 DoS 공격 시 발생하는 문제입니다. ws의 버전 업데이트로 문제를 해결합니다.
- https://github.com/webtoon-today/design-system/security/dependabot/6
-
=> [Chore] override ws version

package-lock.json, packages/feedback/LoadingCircle/package.json
```python
```
- package.json에 선언된 패키지의 이름을 케밥 케이스로 변경합니다. (`npm ci` error)
-
=> [Bugfix] loadingCircle의 패키지 이름을 케밥케이스로 변경합니다.

package-lock.json
```python
```
- guide-text-boxs 패키지 추가 이후 package-lock 파일을 업데이트합니다.
-
=> [Chore] update package lock

packages/feedback/Toast/src/Toast.stories.tsx
```python
```
- toast 스토리북의 typo 수정합니다.
-
=> [Bugfix] toast 스토리북의 typo 수정합니다.

README.md
```python
```
- readme에 레파지토리 설치법을 명시합니다. (main 설치, release tag 설치)
-
=> [Docs] readme에 레파지토리 설치법을 명시합니다.

packages/feedback/LoadingCircle/src/LoadingCircle.stories.tsx
```python
```
- 컴포넌트 이름과 스토리북의 meta title의 스타일을 일치시킵니다. 
- 컴포넌트: 파스칼 케이스 (eg. `LoadingCircle`)
- 커스텀 훅: 카멜 케이스 (eg. `useSortableTable`)
-
=> [BugFix][LoadingCircle] 스토리북의 meta title과 컴포넌트의 이름을 일치시킵니다.

docs/package-lock.json, docs/package.json
```python
```
- docs의 package 버전을 0.1.1로 업데이트합니다.
-
=> [Chore][Docs] docs의 package 버전을 0.1.1로 업데이트합니다.

README.md, dist/Toast/index.d.ts, dist/Toast/index.js, docs/package-lock.json, docs/package.json, docs/src/Component/ReleaseNote.js, package-lock.json, package.json, packages/feedback/LoadingCircle/src/LoadingCircle.stories.tsx, packages/feedback/Toast/src/Recoil/Toast.ts, packages/feedback/Toast/src/Toast.scss, packages/feedback/Toast/src/Toast.stories.tsx, packages/feedback/Toast/src/Toast.tsx
- https://github.com/webtoon-today/design-system/pull/60
- https://github.com/webtoon-today/design-system/pull/61
- https://github.com/webtoon-today/design-system/pull/62
- https://github.com/webtoon-today/design-system/pull/63
- https://github.com/webtoon-today/design-system/pull/64
=> [Release][240711] v1.5.0 토스트 개선, docs 수정 

dist/GuideTextBoxs/index.d.ts, dist/GuideTextBoxs/index.js, packages/input/GuideTextBoxs/src/GuideTextBoxs.tsx
```python
```
- 가이드텍스트 박스의 타입을 지정할 수 있도록 수정했습니다
-
=> [feature] 가이드텍스트 박스의 타입을 지정할 수 있도록 수정했습니다

dist/GuideTextBoxs/index.d.ts, dist/GuideTextBoxs/index.js, package-lock.json, package.json, packages/input/GuideTextBoxs/src/GuideTextBoxs.tsx
- https://github.com/webtoon-today/design-system/pull/66
=> [Release][240711-1] v1.5.1 가이드 텍스트 박스 props 추가

.github/workflows/deploy.yml
```python
```
- release 브랜치 자동 배포 완료 후 pr에 스토리북 url을 코멘트합니다
- 테스트 브랜치: https://github.com/webtoon-today/design-system/pull/65
-
=> [Chore] GitHub action pr comment에 배포된 url을 표시합니다

packages/feedback/Toast/src/Toast.scss, packages/feedback/Toast/src/Toast.stories.tsx
```python
```
- 토스트를 중앙 정렬하고, 마우스 이벤트가 동작할 수 있도록 수정합니다. 
-
=> [Bugfix][Toast] 토스트가 항상 올바른 위치에 올 수 있게합니다.
